[package]
name = "ci-hoover"
version = "0.1.0"
edition = "2021"

[dependencies]
bytesize = "1.3.0"
rayon = "1.10.0"
sysinfo = { version = "0.32.0", default-features = false, features = ["multithread", "disk"] }
