[package]
name = "ci-hoover"
version = "0.1.0"
edition = "2021"

[dependencies]
bytesize = "1.3.0"
envy = "0.4.2"
rayon = "1.10.0"
ron = "0.8.1"
serde = { version = "1.0", features = ["derive"] }
sysinfo = { version = "0.32.0", default-features = false, features = ["multithread", "disk"] }
