name: Build
on:
  push:
    branches:
      - "*"
  pull_request:
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - stable
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.version }}
          components: rustfmt
      - name: test
        run: cargo test
      - name: check formatting
        run: cargo fmt -- --check
      - name: install
        run: cargo build --release && sudo mv target/release/ci-hoover /bin
      - name: run
        run: sudo ci-hoover
